"""
tools/pki/embed_pubkey.py

Public Key Embedding Tool
Requirement: ROT001 - Embed manufacturer public key into PX4 firmware

WHY this tool exists:
  The manufacturer public key (PEM format) lives in pki/manufacturer/public/.
  PX4 firmware (C/C++ on NuttX) cannot parse PEM format — it needs raw bytes.
  This tool converts the PEM public key to a C header file containing the key
  as a byte array, which gets compiled directly into the firmware.

  At boot, the POST module uses this embedded key to verify the stored manifest
  signature — proving the manifest came from us, the manufacturer.

  For LOG001, the same embedded public key is used to encrypt log file hashes.

OUTPUT FORMAT (manufacturer_pubkey.h, app-fw consumer):
  static const uint8_t MANUFACTURER_PUBLIC_KEY_DER[] = { 0x30, 0x82, ... };
  static const size_t  MANUFACTURER_PUBLIC_KEY_DER_LEN = <size>;

  The key is in DER-encoded SubjectPublicKeyInfo format (X.509 standard).
  For RSA-2048, this is approximately 294 bytes.

WHY DER SubjectPublicKeyInfo?
  - OpenSSL's d2i_PUBKEY() accepts this format directly
  - libtomcrypt's rsa_import accepts this format directly
  - Self-describing format — includes algorithm OID and key parameters

SECONDARY OUTPUT (manufacturer_public_der_bytes.h, bootloader consumer):
  Comma-separated raw byte initializer (no array name, no header guard) —
  the PX4 bootloader's stub_keystore #include's this inline as the body of
  CONFIG_PUBLIC_KEY0. Same DER bytes, different formatting.
"""

from pathlib import Path
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

# Paths relative to project root
PROJECT_ROOT     = Path(__file__).resolve().parent.parent.parent
PUBLIC_KEY_PATH  = PROJECT_ROOT / "pki" / "manufacturer" / "public" / "manufacturer_public.pem"

# Output goes into our firmware directory where PX4 can find it
FIRMWARE_INCLUDE_DIR = PROJECT_ROOT / "firmware" / "include"
OUTPUT_HEADER_PATH   = FIRMWARE_INCLUDE_DIR / "manufacturer_pubkey.h"

# Bootloader consumer — comma-separated bytes, no array decl/guard.
# Included verbatim by the PX4 bootloader's stub_keystore via CONFIG_PUBLIC_KEY0.
BOOTLOADER_BYTES_PATH = PROJECT_ROOT / "pki" / "manufacturer" / "public" / "manufacturer_public_der_bytes.h"

# RSA-2048 DER SubjectPublicKeyInfo is ~294 bytes (varies slightly)
EXPECTED_RSA_KEY_BITS = 2048


def pem_to_der(public_key_pem: bytes) -> bytes:
    """
    Convert a PEM-encoded public key to raw DER bytes.

    The PEM format is just base64(DER) wrapped in header/footer lines.
    We load the key and re-export it in DER format.

    Returns:
        DER-encoded SubjectPublicKeyInfo bytes (~294 bytes for RSA-2048)
    """
    public_key = serialization.load_pem_public_key(public_key_pem)

    # Verify it's actually an RSA key with the expected size
    if not isinstance(public_key, rsa.RSAPublicKey):
        raise TypeError(
            f"Key is not an RSA public key (got {type(public_key).__name__}). "
            "Only RSA-2048 is supported by the PX4 secure boot module."
        )
    if public_key.key_size != EXPECTED_RSA_KEY_BITS:
        raise TypeError(
            f"Expected RSA-{EXPECTED_RSA_KEY_BITS}, got RSA-{public_key.key_size}. "
            "Only RSA-2048 is supported by the PX4 secure boot module."
        )

    der_bytes = public_key.public_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    return der_bytes


def der_to_c_header(der_bytes: bytes, array_name: str = "MANUFACTURER_PUBLIC_KEY_DER") -> str:
    """
    Convert raw DER bytes to a C header file containing a static byte array.

    The output is safe to include in any C or C++ file.
    The #pragma once guard prevents double-inclusion.

    Args:
        der_bytes:  Raw DER key bytes
        array_name: Name for the C array (default: MANUFACTURER_PUBLIC_KEY_DER)

    Returns:
        Complete C header file as a string
    """
    # Format bytes as hex with 8 per line for readability
    hex_values = [f"0x{b:02x}" for b in der_bytes]
    lines = []
    for i in range(0, len(hex_values), 8):
        chunk = hex_values[i:i+8]
        line = "    " + ", ".join(chunk)
        # Add trailing comma if not the last line
        if i + 8 < len(hex_values):
            line += ","
        lines.append(line)

    hex_block = "\n".join(lines)

    header = f"""\
/**
 * manufacturer_pubkey.h
 *
 * AUTO-GENERATED by tools/pki/embed_pubkey.py — DO NOT EDIT MANUALLY
 *
 * Manufacturer RSA-2048 public key in DER-encoded SubjectPublicKeyInfo format.
 * Used by the secure_boot module to:
 *   - Verify firmware manifest signatures (POST001)
 *   - Verify firmware update bundle signatures (UPD001)
 *   - Encrypt audit log file hashes (LOG001)
 *
 * Key size:    {len(der_bytes)} bytes (DER SubjectPublicKeyInfo)
 * Algorithm:   RSA-2048 (112-bit security, NIST SP 800-57 R5)
 * Format:      X.509 SubjectPublicKeyInfo (DER)
 *              Accepted by OpenSSL d2i_PUBKEY() and libtomcrypt rsa_import()
 *
 * To regenerate: python tools/pki/embed_pubkey.py
 * WARNING: Regenerating with a different key will invalidate all signed manifests.
 */

#pragma once

#include <stdint.h>
#include <stddef.h>

/* {len(der_bytes)}-byte RSA-2048 public key, DER SubjectPublicKeyInfo format */
static const uint8_t {array_name}[] = {{
{hex_block}
}};

static const size_t {array_name}_LEN = {len(der_bytes)}u;
"""
    return header


def der_to_bootloader_bytes(der_bytes: bytes) -> str:
    """
    Render the DER bytes as a comma-separated initializer for the PX4 bootloader.

    The bootloader's stub_keystore #include's this file inline as the body of
    CONFIG_PUBLIC_KEY0 — so it must NOT contain a #pragma once, array name,
    or trailing semicolon. Just bytes.
    """
    hex_values = [f"0x{b:02x}" for b in der_bytes]
    lines = []
    for i in range(0, len(hex_values), 12):
        chunk = hex_values[i:i + 12]
        line = ", ".join(chunk)
        if i + 12 < len(hex_values):
            line += ","
        lines.append(line)
    return "\n".join(lines) + "\n"


def generate_header(
    public_key_path: Path = PUBLIC_KEY_PATH,
    output_path: Path = OUTPUT_HEADER_PATH,
    bootloader_bytes_path: Path = BOOTLOADER_BYTES_PATH,
) -> str:
    """
    Full pipeline: load PEM key → convert to DER → write both consumer files:
      - app-fw header (manufacturer_pubkey.h, with array decl + guard)
      - bootloader byte-list (manufacturer_public_der_bytes.h, raw bytes)
    """
    if not Path(public_key_path).exists():
        raise FileNotFoundError(
            f"Public key not found at {public_key_path}. "
            "Run tools/pki/keygen.py first."
        )

    pem_bytes = Path(public_key_path).read_bytes()
    der_bytes = pem_to_der(pem_bytes)
    header_content = der_to_c_header(der_bytes)

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header_content, encoding="utf-8")

    bootloader_bytes_path = Path(bootloader_bytes_path)
    bootloader_bytes_path.parent.mkdir(parents=True, exist_ok=True)
    bootloader_bytes_path.write_text(der_to_bootloader_bytes(der_bytes), encoding="utf-8")

    print(f"[OK] App-fw header:     {output_path}")
    print(f"[OK] Bootloader bytes:  {bootloader_bytes_path}")
    print(f"     Key size: {len(der_bytes)} bytes (RSA-2048 SubjectPublicKeyInfo DER)")
    return header_content


if __name__ == "__main__":
    generate_header()
