"""
tools/pki/embed_pubkey.py

Public Key Embedding Tool
Requirement: ROT001 - Embed manufacturer public key into PX4 firmware

WHY this tool exists:
  The manufacturer public key (PEM format) lives in pki/manufacturer/public/.
  PX4 firmware (C/C++ on NuttX) cannot parse PEM format — it needs raw bytes.
  This tool converts the PEM public key to a C header file containing the key
  as a byte array, which gets compiled directly into the firmware.

  At boot, the POST module uses this embedded key to verify the stored manifest
  signature — proving the manifest came from us, the manufacturer.

OUTPUT FORMAT (manufacturer_pubkey.h):
  static const uint8_t MANUFACTURER_PUBLIC_KEY_DER[] = { 0x30, 0x59, ... };
  static const size_t  MANUFACTURER_PUBLIC_KEY_DER_LEN = 91;

  The key is in DER-encoded SubjectPublicKeyInfo format (X.509 standard).
  For ECDSA P-256, this is always exactly 91 bytes.

WHY DER SubjectPublicKeyInfo?
  - libtomcrypt's ecc_import_x509() accepts this format directly
  - It includes the curve OID (secp256r1) so libtomcrypt knows which curve to use
  - No extra parameters needed — the format is self-describing
"""

from pathlib import Path
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec

# Paths relative to project root
PROJECT_ROOT     = Path(__file__).resolve().parent.parent.parent
PUBLIC_KEY_PATH  = PROJECT_ROOT / "pki" / "manufacturer" / "public" / "manufacturer_public.pem"

# Output goes into our firmware directory where PX4 can find it
FIRMWARE_INCLUDE_DIR = PROJECT_ROOT / "firmware" / "include"
OUTPUT_HEADER_PATH   = FIRMWARE_INCLUDE_DIR / "manufacturer_pubkey.h"

# Expected DER size for P-256 SubjectPublicKeyInfo (always 91 bytes)
EXPECTED_DER_SIZE = 91


def pem_to_der(public_key_pem: bytes) -> bytes:
    """
    Convert a PEM-encoded public key to raw DER bytes.

    The PEM format is just base64(DER) wrapped in header/footer lines.
    We load the key and re-export it in DER format.

    Returns:
        DER-encoded SubjectPublicKeyInfo bytes (91 bytes for P-256)
    """
    public_key = serialization.load_pem_public_key(public_key_pem)

    # Verify it's actually P-256 — fail loudly if wrong curve
    if not isinstance(public_key, ec.EllipticCurvePublicKey):
        raise TypeError("Key is not an EC public key")
    if not isinstance(public_key.curve, ec.SECP256R1):
        raise TypeError(
            f"Expected P-256 (secp256r1), got {public_key.curve.name}. "
            "Only P-256 is supported by the PX4 secure boot module."
        )

    der_bytes = public_key.public_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    return der_bytes


def der_to_c_header(der_bytes: bytes, array_name: str = "MANUFACTURER_PUBLIC_KEY_DER") -> str:
    """
    Convert raw DER bytes to a C header file containing a static byte array.

    The output is safe to include in any C or C++ file.
    The #pragma once guard prevents double-inclusion.

    Args:
        der_bytes:  Raw DER key bytes
        array_name: Name for the C array (default: MANUFACTURER_PUBLIC_KEY_DER)

    Returns:
        Complete C header file as a string
    """
    # Format bytes as hex with 8 per line for readability
    hex_values = [f"0x{b:02x}" for b in der_bytes]
    lines = []
    for i in range(0, len(hex_values), 8):
        chunk = hex_values[i:i+8]
        line = "    " + ", ".join(chunk)
        # Add trailing comma if not the last line
        if i + 8 < len(hex_values):
            line += ","
        lines.append(line)

    hex_block = "\n".join(lines)

    header = f"""\
/**
 * manufacturer_pubkey.h
 *
 * AUTO-GENERATED by tools/pki/embed_pubkey.py — DO NOT EDIT MANUALLY
 *
 * Manufacturer ECDSA P-256 public key in DER-encoded SubjectPublicKeyInfo format.
 * Used by the secure_boot module to verify the firmware manifest signature.
 *
 * Key size: {len(der_bytes)} bytes (standard for P-256 SubjectPublicKeyInfo)
 * Curve:    secp256r1 (NIST P-256)
 * Format:   X.509 SubjectPublicKeyInfo (DER) — accepted by libtomcrypt ecc_import_x509()
 *
 * To regenerate: python tools/pki/embed_pubkey.py
 * WARNING: Regenerating with a different key will invalidate all signed manifests.
 */

#pragma once

#include <stdint.h>
#include <stddef.h>

/* {len(der_bytes)}-byte ECDSA P-256 public key, DER SubjectPublicKeyInfo format */
static const uint8_t {array_name}[] = {{
{hex_block}
}};

static const size_t {array_name}_LEN = {len(der_bytes)}u;
"""
    return header


def generate_header(
    public_key_path: Path = PUBLIC_KEY_PATH,
    output_path: Path = OUTPUT_HEADER_PATH,
) -> str:
    """
    Full pipeline: load PEM key → convert to DER → write C header file.

    Args:
        public_key_path: Path to the PEM public key file
        output_path:     Where to write the generated .h file

    Returns:
        The generated header content as a string
    """
    if not Path(public_key_path).exists():
        raise FileNotFoundError(
            f"Public key not found at {public_key_path}. "
            "Run tools/pki/keygen.py first."
        )

    pem_bytes = Path(public_key_path).read_bytes()
    der_bytes = pem_to_der(pem_bytes)
    header_content = der_to_c_header(der_bytes)

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header_content, encoding="utf-8")

    print(f"[OK] Public key header written to: {output_path}")
    print(f"     Key size: {len(der_bytes)} bytes (P-256 SubjectPublicKeyInfo DER)")
    return header_content


if __name__ == "__main__":
    generate_header()
